const initialReactions = [
  "I think it's a great program for young athletes. It helps them stay on track with their sports goals and keeps them energized and focused on playing at the best level. I like that it has different videos and exercises to help young athletes perform at their best overall. It's available at a great price and I would definitely be willing to pay for this for my son.",
  ,
  "Breastfeeding was so draining and dehydrating! I would’ve definitely used this product to support my feeding and vitality.",
  "This is very interesting! I do think that for the right person this could be very helpful. Many people do not truly understand the tone they talk in or are unable to see how they come across, and this sounds like it could potentially provide some insight that is not biased. I find it appealing as I am in the field of therapy and social work and could definitely find a use for it for a number of clients who struggle with communication. This could be a great tool for therapists if clients would honestly and accurately use it!",
  "I think this idea is a great idea. I believe the ease of use will be a contributing factor.",
  "I think it's a great idea and would work successfully.",
  "It's a great idea for people with one to two cats. However, I guess it doesn't matter how many cats you have. If one has it, then it's worth treating all of them.",
  "It's a great idea because most people like to adventure a little and try new things. Spicy food is one of them.",
  "I think it's a great idea that could be expanded upon.",
  "I think it sounds like a great idea for young athletes to give them a mental and physical edge above others.",
  "I think that this is a great idea for nursing moms to get the nutrients and supplements they need to nourish their babies.",
  "I think it sounds like a great idea and it does appeal to me personally.",
  "A guide to help build a better relationship with your partner. With great ideas.",
  "Yes, I think it would be very successful because it made me feel good just reading it. It appeals to me in terms of love in a cup of my favorite coffee.",
  "I think the “love” copy goes a little too far. It just needs to tell the potential customer how wonderful and important a cup of coffee can be for you or another person that would appreciate the gesture. The “thank you” cup of coffee is what the ad is trying to express but again, goes a smidge too far.",
  "I think the technology for a great idea is there and with the right marketing could be successful, especially for people like me who rely on contact lenses for everyday activities.",
  "I think it’s a great idea and a lot of people will agree with it.",
  "I think it sounds like a great idea. It sounds like a nice place to get coffee and breakfast in one spot whenever you want.",
  "I think it’s a decent idea. Considering the times we live in now, it sounds appropriate, fun, delicious, refreshing, and relatively simple to accomplish.",
  "I think it’s a great idea that we can continue to relate our roots in preparing foods that are good for our budget, also simple and wholesome for the entire family and good for your health.",
  "I think it’s a great idea, to have an easy go to recipe, that anyone can prepare in a minutes.",
  "I think it is a great home town success story that provides unique and delicious flavors.",
  "I think it’s a great idea to help your plants and lawn grow better and stronger.",
  "I think it’s a great idea to help your plants and lawn grow better and stronger.",
  "It's a great idea. I like it. I truly do.",
  "I think it's a great idea. It's a good objective and the premise of more flavor instead of just blind heat is great. It appeals to me personally.",
  "I think it's a great idea!",
  "Personally, I like the idea. Starbucks take home is a great idea. I can fix the coffee exactly as I want it. Superb idea.",
  "This is a very great idea and if it became an affordable asset to purchase for people that wear contacts and glasses everyday it would be great. It would help a lot for those who don’t want to get corrective surgery and it would feel great knowing that it is also helping the health of your eyes.",
  "Yes, I think this would be a great idea! A way for people to get together, enjoy your morning or an afternoon average. I think it's a great idea.",
  "I think this is an awesome idea. It helps reduce costly vet visits. But it also allows you to be certain whether something is actually wrong.",
  "I do if I can understand the technology a bit better. I feel like I might invest in one depending on the price. I would like to know what's wrong with my cat.",
  "I think that it’s a great idea! I don’t like anything too spicy, but my husband loves it!",
  "I think this is good. My spice tolerance has gone up over the years, but I am still not on the level of my sister or her spouse. So she tends to cook meals we share with a lower spice level and then adds extra on her plate.",
  "Quite impressive. At $10 per month, it sounds like it would be worth a shot. If nothing else, for motivation.",
  "I think this idea will be successful, because it’s new and fresh. Many people like to be challenged and try out new things.",
  "I wish I knew about something like this, if there was one around that time. It's very overwhelming just delivering, especially if you have more kids and being stressed and overthinking can really mess with your brain and body, and you won't be able to produce like you want/need.",
  "I do because I had a hard time breastfeeding my second baby because I wasn't about to eat how I needed to too produce enough milk.",
  "I think it’s a cute idea if your relationship is maybe in a slump. A new way to address new topics and open communication. I think it would be useful as long as both people agree to use it regularly.",
  "I think it’s a good concept. Allows people who do not have a support system to have a vent allowing for better well-being - mental/emotional.",
  "At first glance, I wasn't sure I would be interested. After reading the explanation, I am interested in this app. I thought of my relationships. This does appeal to me personally.",
  "Everyone needs that little bit of kindness, such as the perfect cup of coffee, made like you like it. We all have stress but sometimes coffee, iced coffee, or as I prefer a Caramel Frappuccino, can make your day a little better as you sip and relax a minute.",
  "It is an intriguing idea—I would be curious to check it out to see how well it is executed. If done well, I think it could become popular/successful.",
  "I think this is a great idea. I love a variety of drink options that are different than regular soda. I am really into tea and coffee drinks that aren't heavily sugared down, but I don't have many options besides Starbucks (whom I don't like to support). I also love the idea that I can get a sweet snack on the go without having to go into a store or buy a huge container of a specific item. Also, I think it will depend on the price of the items. With the economy being in crisis, people are looking to save any penny they can. Depending on the area, I think this will be successful. (Not around any Dunkin Donuts, Panera Breads, Crumbl Cookies, etc. )",
  "I think the story is nice and I think they will be successful because I can see someone like me who loves food purchasing items from this brand and supporting them.",
  "I feel like its speaking yo regular people like me. I worry when I want to try new items and recipes.",
  "It's an ad that was colorful and informative and something I need.",
  "I think it will be very successful because people are always looking for good ways to help their grass and yards look better.",
  "I absolutely LOVE this idea! There are often times that I worry and don't want to find out too late because once symptoms start showing with my cat, it is usually pretty bad by that point. This way I could catch it way sooner!",
  "I think it would be ideal because it would alert you ahead of time before an infection is too bad and lets you know so you can get vet care immediately.",
  "Yes, it would be useful because it could catch an issue early before it gets bad. It could save your cat from being in any pain early.",
  "YES THE IDEA WOULD BE VERY SUCCESSFUL BECAUSE SOMEBODY CAN TAKE CARE OF THEIR CAT WITHOUT GOING TO VETERINARY ALL THE TIME.",
  "Sounds like a great idea. I love a good hot sauce, but I find it annoying when there is too much heat, so I end up not being able to taste my food. A hot sauce that perfectly balances heat and flavor sounds euphoric.",
  "This sounds good because I love hot sauce, but personally it feels like the flavor is just fire at this point. I wish I could enjoy more of the spice taste behind it without burning my tongue off.",
  "I'm not sure about the spicy and fruity taste together, but it would be something I would try. I rather taste the food, the sauce I mean, the flavor of it, than the spiciness.",
  "I'm curious what the flavors are going to be. I like hot stuff but it's hard to find the right amount.",
  "Yes, I think it would be very successful. It would help with personal training and allow my son to set personal goals. We look at YouTube videos and all the video footage we can find. This would help him a lot with technique and getting rid of bad habits.",
  "I think this could really successful, because it is online. Most in-person classes are a turn-off for the youth. This isn't too invasive for teens' day-to-day life, and it isn't too expensive. If done right, this could be very successful.",
  "I would like it how it is. I would be open to trying it.",
  "I wish I knew about something like this, if there was one around that time. It's very overwhelming just delivering, especially if you have more kids and being stressed and overthinking can really mess with your brain and body, and you won't be able to produce like you want/need.",
  "I think it is a great concept that has the possibility of becoming a hit with new moms as long as there are no bad side effects, and it is tasty.",
  "I think there are some people that would use it as more relationships are being found via the internet instead of meeting people.",
  "It could be good but would take all parties being open minded.",
  "People’s daily existences can be improved by someone showing they care, and giving them a cup of Starbucks is a good way to demonstrate it. The ad is appealing because everyone has bad days sometimes and everyone likes to feel valued.",
  "It says we are in the coffee business to stay.",
  "It made I feel a bit better about SB. They don't seem as snooty.. I guess?",
  "I think it’s a good idea and it would be successful. It seems really well thought out and appeals to me because this is something I personally would be interested in due to my bad vision. It seems quite safe too.",
  "It sounds good if it works. Switching from glasses to contacts can be difficult, and by the end of the day your eyes really begin to hurt. Would be good to have a solution to that.",
  "Personally, I would love to have this because having to put contacts in and out is such a hassle, not even mentioning them ripping in your eye, or tearing, or folding, or drying out.",
  "I think it is a great idea and that it would be successful. Because if it is selling some of the same drinks as a regular McDonald's, people will love it. I know me personally, I love the sweet tea and frappes, but I usually opt out of going and getting one because the lines are usually too long or the lobby is full. Me personally, I don't like waiting just for something to drink.",
  "I like it. I love how it's not just coffee... I feel that people would place an order for pick up more. I don't like having to go in for a pick up order. Driving through would be so much faster!",
  "I think it would be successful because people with no imagination would have their dinner already planned in detail. The imaginative person would leave something to chance.",
  "Looks like it will be used by many cooks.",
  "Yes, because a lot of people are health conscious. They don't want chemicals; they want nutritional food.",
  "Yes, they should work on more organic fertilizers.",
  "I love concepts and ideas, but this is not affordable for so many people. Only geared towards the rich or those who have disposable income.",
  "It doesn't appeal to me personally, however, I think it might be beneficial to couples who are having problems with communication.",
  "This sounds absolutely wonderful! However, sadly, I don't associate employees at McDonalds with barista skills. I certainly do hope this can work and that it does take off. Sadly, I have my reservations regarding employees and consistency of products.",
  "Yes, I would purchase it if the price was reasonable. It would be very useful to have an indication of issues before having a vet appointment.",
  "My cat uses the yard. I have no opinions on cat litter.",
  "If it monitors a cat's health it would be a good product.",
  "It depends on the price of the pouches, if it's too expensive it might just be worth it to save for an emergency vet visit for when the cat shows signs.",
  "Yes because people want something that actually tastes good.",
  "I like it if it's not too spicy.",
  "Sounds appealing. I can't do heat.",
  "Of course this would be successful. I do not think I would use it but some younger people will.",
  "It will be great, but the price is a little high.",
  "I think this is a very cool idea as long as it works, I’ve used one of these methods before, and it felt like it made no difference but I also didn’t drink it much because the taste was nasty. I believe it would sell, especially offering a bulk size option, especially to mommas who breastfeed longer.",
  "I think it would be successful. Mothers struggle to put the nutrients we need in our bodies after birth.",
  "Breastfeeding was so draining and dehydrating! I would’ve definitely used this product to support my feeding and vitality.",
  "I love it and I need it. Is this real? I want to download it right now. My husband never talks to me, never hugs or kisses me anymore. After 35 yrs of marriage I feel so lonely.",
  "I am wary of having an app analyze conversations. Having guided prompts is interesting. Most people aren't self-aware, so I think that this could help others. This does not appeal to me personally.",
  "I think it would be successful due to some people having communication issues. I would use it.",
  "Yea. I believe it will be the basis for an ad. Because they are relating why some people might drink coffee or drink coffee from Starbucks. And relating it to like actual irl situations.",
  "It would be a successful ad because it is appealing to those that feel like life is going so fast and have no extra time to do anything and always feel like rushed.",
  "It will be successful because everyone doesn't have time to stop at the nearby drive-thru, and having it before you leave home would be much easier.",
  "I like the message Starbucks wants to give. The message is for me, but I've tried Starbucks many times, and it's not my preferred coffee.",
  "I think this is a good idea especially with mentioning that about how contacts can be uncomfortable to wear because you're reaching your target market of audience. We hate contacts as they're really irritating and if you can in fact offer this then I think it's an amazing idea.",
  "I think this is a good idea. It's an issue I definitely struggle with, especially towards the end of the day. If it were to work, I believe it could be very successful as long as it's not too much more expensive and a similar price to others.",
  "I think it is very innovative, especially since there isn’t too much vision-related tech. It appeals personally, but I don’t know if it would be successful. It’s a risk.",
  "We are in a country accustomed to immediate and fast service, and at the same time, the products must be very varied and diverse to please even the most demanding or extravagant palate, so I think that this new idea of a soft drink restaurant would be a novel alternative.",
  "This sounds very much like a more modernized version of Starbucks, in the same way that self-check out is to supermarkets. I do believe this would be successful, as it would make things go faster and people get the products and flavors they want.",
  "Not sure if it would be successful, but it sounds a lot like Starbucks. I would try it, especially if prices were low.",
  "Yes, I do think it could be successful. When you do not live in a big city meals have to be planned out and delivery isn't as easy. So some help putting together meals and trying new things is important.",
  "I like the idea, but I don't know if people entertain the way they used to. Pickling homegrown produce might make a comeback with rising grocery prices, though.",
  "I would give it a shot because honestly when we flavor our meats, u definitely not tasting it. Any help would be appreciated.",
  "Would be effective.",
  "Thought that’s the best way to fertilize.",
  "Depends on what it is served on.",
  "There's a possibility that this app may be useful to certain individuals.",
  "It only indicates one thing. And it might be correct. I wouldn’t buy this.",
  "Sounds great to me - I like spicy foods - even can my salsa and ferment hot sauce.",
  "It sounds like it could be a delicious way to enhance meals without the heat.",
  "I think the sauce would make a big difference and add heat and flavor to the meal.",
  "Sure, it could be if people were receptive and creative.",
  "It might be successful depending on the price and more information I feel is needed. It sort of appeals to me personally but it sounds weird at the same time.",
  "I like it.",
  "Yes! I would love this! We do drift apart at times, and reconnection sounds like just what we need. I would be thrilled to try this out.",
  "Yes, it would be successful for someone like me, as I definitely relate to the feeling of wanting to be prepared for the craziness of life but sometimes feeling so unmotivated and tired. As a stay-at-home mom, I love the idea of being able to create coffee beverages at home.",
  "I think it would be very successful. It is very relatable to me and I think many others. When people come together for anything they usually offer coffee no matter what the occasion. It’s a nice thought to put in your head that when you are drinking that coffee to just take a minute to take it all in.",
  "It does evoke some emotions when thinking of family and all of the cozy memories, or the hot summer days with an iced coffee. However, I feel like the ad doesn't necessarily match the item/product being sold.",
  "The concept of a next-generation contact lens that combines vision correction, hydration support, focus enhancement, and irritant protection is very compelling. It addresses real and growing issues many people face due to increased screen time and environmental factors—eye fatigue, dryness, and discomfort. It is potentially successful and appeals to me, especially the part about reducing fatigue and keeping eyes hydrated during long hours of focus.",
  "I really like the concept. For years, contacts haven't drastically changed.",
  "I think it’s a great idea that will bring in many people. I personally would definitely go to it, although it may be not too often.",
  "The idea is good in theory, and I trust McDonald’s more than most other brands to make the ease and speed of service happen. I would be curious how comfortable customers are with the info about preferences being tracked.",
  "It all sounds pretty good to me, who doesn't like fresh ingredients?",
  "Yes, it will be successful. It’s about showing up and making your own.",
  "It is an ad promoting Pennington. It would be successful. It is a helpful lawn product. It makes me interested in buying the product.",
  "It's just like hydro seeding but for flowers. I like the idea.",
];

const contextPrompts = [
  "I could imagine my teenage son using this before his football game. It would be great in helping him get focused for the game and be hyped for playing the best he can. I also can see him using it between practices when he needs a little push to play better.",
  "A stay at home mom, or a mom working by and pumping at work, could both benefit from this product.",
  "As someone in the therapy field, I could definitely see a client looking for help with relationships being willing to use this to help communicate with their partners. Especially if their motivation is to show their partner how they are speaking to them. Or to help their therapist see how things occur at home.",
  "Someone who cares for their cat a great deal and wants to make sure they are healthy.",
  "It would be perfect for someone like me who is always worrying if something is wrong with one of my fur babies if they are acting a little off.",
  "The cat litter box has a terrible stench that's not normal.",
  "A foodie person and one that loves to challenge themselves.",
  "I could see my child wanting to use this during the sports season to heighten their performance.",
  "I would think high school kids maybe trying to gain any edge they can to make a high school sports team, and they think it would make them play just that much better.",
  "If they're wanting to increase the amount of milk they produce, this will help them.",
  "I think people like my husband and I—who would love to do couples’ therapy but who doesn’t have the time in our schedule for it—could use it since it can be used at anytime convenient to you.",
  "Learning how to deal with disagreement and learn to work it out.",
  "Someone who had been stressed out might need a cup of coffee to relax and someone offering them a cup is like love in a cup.",
  "It is about the value and appreciation one can receive by getting a 'thank you' cup of coffee from someone else. Anyone that has done a favor or a gesture that is worth the reception of a perfectly brewed and prepared cup of coffee should receive the 'thank you' cup. This cup is not only representative of a thank you but can also be used to brighten up someone’s day. The 'thank you' cup is akin to a thank you note. Someone took time to prepare not any cup of coffee but a perfect cup of 'thank you' coffee.",
  "Someone who spends a lot of time out and about or even someone who spends a lot of time in front of screens. This really can appeal to a wide range of people.",
  "People who have a very open mindset and who are ready to accept changes.",
  "I could see myself taking my children by in the morning to grab breakfast on the way to school, and I could get coffee at the same time.",
  "Number one is when you want that quickly as you make it to your destination on time. Two, great for travelers and truckers. 3, something everyone would enjoy.",
  "I think a lot of families and single people are more cautious of our health in these times that we’re living in. It will be very attractive for them to start buying and enjoying all the recipes which are wholesome with great ingredients. I think it’s a plus.",
  "Anyone that’s want to be able to make quick meals would find this interesting.",
  "Someone who appreciates authentic old-fashioned pickled flavors.",
  "People that like to take care of plants and their lawn.",
  "People that like to take care of plants and their lawn.",
  "All cat lovers will love this product.",
  "I think most people that enjoy some spice would love it. I think adding a good hot sauce elevates most dishes.",
  "A mom on the go or a mom who doesn't drink much would be able to use this product and get more nutrients needed to breastfeed.",
  "I would love this. I like my coffee to be an adventure through its aroma & taste. I need it to take me away.",
  "For people like myself that have to wear contacts and glasses every day all day, but also their eyesight is not bad enough for corrective eye surgery.",
  "I think kids would enjoy watching the drinks being concocted in the back. And I also think I would probably enjoy watching it as well. I also think the games are a brilliant idea to keep people busy while they're waiting. And the music is fabulous as long as it's kept low enough so that people can still communicate.",
  "Well, obviously, the type of person who would love this type of product is a cat lover. A product like this would be incredibly invaluable to them, as they can keep a close eye on the health of their furbaby. I know a product like this would have been incredibly useful for my cat. I could see free samples of this product being handed out at the store where I shop.",
  "My sister owns a cat and loves her cat. She doesn't have kids so would most likely splurge.",
  "We often make soups and chilis so this would be a great opportunity.",
  "Probably my sister would like it. She loves spices and hot sauces, but likes when they are flavorful rather than just hot.",
  "I believe women would use it most. Especially teens trying to ready themselves for an important meet or game.",
  "I think any person would enjoy using this idea. Especially someone who enjoys sports.",
  "I think any breastfeeding mother would love this because it would put her mind to rest, since she doesn't have to be stressed out to use it, but it would still work even if she's stressed out. Unlike without a product like this, someone might not be able to produce because of stress.",
  "Someone like me with not being able to chew because of bad teeth without dental insurance.",
  "Any couple that wants to add new thoughts or information to their ordinary regular routine conversations.",
  "If someone lacked a support system and needed to get something off of their chest or ease their mind by sharing with someone. Maybe an embarrassing or shameful situation where someone is not comfortable sharing with someone in person.",
  "Any relationship that involves people should use this app. If it does what it claims to do, it could assist many people who think they communicate effectively in pointing out, in kind ways, the misgivings involved in their communication.",
  "I know I enjoy my Caramel Frappuccino whenever I know I am going to have a busy day. If I am going to drive a long distance, this also helps to make the drive seem a little less stressful. And sometimes I just feel like the need for a Caramel Frappuccino. There are so many times that most of us can just take a minute and enjoy the coffee that makes them happy.",
  "I think this could appeal to people who are health conscious, young people, busy parents/employees with limited free time.",
  "I would go there in the morning before work for a coffee or tea. I also would go there to buy a present for one of my friends.",
  "Someone who cooks and is interested in supporting hard workers. As someone who cooks I understand fresh vegetables and herbs are key in my dishes. What better way than to support Mrs. Wages.",
  "Someone who is just a normal human wanting to create something special.",
  "For the gardener, people love plants.",
  "To purchase their products because it's better than the other yard products on the market.",
  "There are times when my otherwise indoor cat gets out around my younger daughter, and does not come home for a day or 2. It is times like that that I would want to test her when she returns because I don't know what she was in contact with.",
  "When you have multiple or any cats whatsoever it would be perfect, and I think a lot of people would buy and rely on this product.",
  "I have tried this before because my cat was acting weird when she would go into the litter box. Luckily, she was ok.",
  "MY MOTHER LOVES CATS. SHE WOULD LOVE IT.",
  "A hot sauce that brings a vibrant flavor and just the right amount of kick can and will be used everywhere. I'd put it on everything.",
  "I would personally love this, but at dinners, my family uses hot sauce a lot, and with the catch that it's less hot without not being spicy, would get me and my family.",
  "My father would love to try it. He makes his own hot sauce, so I knew he'd love to try it as well as my sister. They love spicy food, but I think my son really would like to try it to see about the flavor of it.",
  "I can picture my whole family trying this. We would try it with burgers, chicken and pork steaks.",
  "I can see my son getting help with his footwork and technique on pass rushing. And getting help eating the right foods to keep him full of energy. I can see my son using this in the summer time.",
  "My daughter would use this when she's transitioning into a higher grade or different sport interest. She tends to get really involved and emotional about sports. I can see an overhyped teen without steady focus and methods of controlling her mental and nutrition. This would be good for them.",
  "It depends on the person who would want to use it. Everybody is different.",
  "I think any breastfeeding mother would love this because it would put her mind to rest, since she doesn't have to be stressed out to use it, but it would still work even if she's stressed out. Unlike without a product like this, someone might not be able to produce because of stress.",
  "It would be ideal for moms that have depleted nutrition.",
  "I think a person that wants a relationship that includes snuggling, talking, and as my husband puts it 'bonding.'",
  "Someone who wants to know more but has a partner who often gives 1 word answers.",
  "A regular or frequent coffee drinker would appreciate a cup of their favorite Starbucks when they’re having an especially grueling day at work.",
  "This is just a reinforcement statement and really says nothing new.",
  "I felt like I would actually try SB products at home.. give them a chance and see if they are as good as the in-store brew.",
  "I feel like a person who has quite a bit of trouble with eyesight and struggles to keep up with their contact lens subscription might be interested in this idea.",
  "People on the go who do multiple activities a day such as looking at computers, exercising, socializing.",
  "I would love this including my family since we all wear contacts and hate having to put them in. People who wear should love it.",
  "I think a person who only has a short amount of time on their break from work who wants something to drink would really love this. Or someone who is in a hurry and needs something to drink.",
  "Any wanting to do something outside of home!",
  "The imaginative person who enjoys creating a last minute triumph.",
  "A person who enjoys cooking and trying new flavors.",
  "Depending on what kind of dishes she creates.",
  "The product itself.",
  "I would definitely use if I could afford because excellent product. The only issue would be cost for most.",
  "Maybe in a relationship where a partner is feeling ignored, unappreciated, or distant.",
  "This is just as the advertisement suggested. A pick me up in the middle of the day. Hopefully consistency will be a must with employees and management.",
  "Anyone who has cats could use this product.",
  "I honestly have no idea at all.",
  "A busy person who wants a product to make cat parenting easier.",
  "Probably single cat owners. That way you don't have to guess which cat it could be. Plus, single people probably have more time to pay attention to these kinds of things.",
  "Yes, especially if it actually has flavor.",
  "I think it would be good on chicken wings.",
  "Barbecue and anyone really.",
  "I do believe athletes would but not just athletes anyone.",
  "In a Youth Team sport or school team sport.",
  "I think a woman who would love this product are moms who are producing little in milk and need to boost their supply, and yes I believe many moms would use this product especially if they are interested in breastfeeding for as long as they can. I think as long as the product does what it’s supposed to do and does as advertised there would be no problems in the sale of this item.",
  "Someone who struggles with eating and caring for themselves with a baby, mothers who are sleep deprived.",
  "A stay at home mom, or a mom working by and pumping at work, could both benefit from this product.",
  "I would use it to start talking with my husband when he is being cold and mean to me.",
  "I think that people that are in therapy might like this. It would probably appeal to younger generations. It might also be a compromise if one person wants to go to therapy and the other doesn't.",
  "Someone who has difficulty putting into words their feelings or thoughts.",
  "The type of person that would love this is people mid age or early 20s. Those are adults, and they tend to be very tired and need to drink something that will gain them energy.",
  "It feels relatable to everyone that has a hard time with having extra time on their hands and one that is always in a hurry.",
  "It would be for a really busy early morning riser on the go all the time person.",
  "I like how it spreads kindness. I love when my coworkers show up with my favorite coffee from McDonald’s.",
  "The type of people who would love this are short-sighted and long-sighted issued people and especially contact lenses wearers.",
  "Students first come to my mind for late night revision/work sessions after a long day of work. Also, anyone with an office job, maybe a bird watcher too.",
  "A person worried about their eye’s health. Someone who is trying to use less technology for the sake of their eyes would find this appealing.",
  "Eventually my family and I would like to live that experience. We like to try new things and I think it would be a great opportunity to discover this new business and how interesting and attractive it is. So we would surely go as soon as it was launched on the market.",
  "Those of us who love drinks, especially caffeinated, would try it out. If anything, it would be great to try it out with friends or on a date as one of those 'things to do in [insert city name].'",
  "Grabbing a quick drink starting out on a road trip. Or someone who needs a coffee and didn't have time to make it.",
  "I think people interested in making healthier choices would benefit the most.",
  "I think the dips would be a hit with football parties and such. Or for Mediterranean diet enthusiasts, salad dressings that are outside the usual store selection.",
  "For anyone that wants to add a little bit more spark or flavor in their dishes.",
  "A person who wants a nice yard.",
  "Average person no one special.",
  "Might be good on pork.",
  "Loved ones who are out of town.",
  "An actual veterinarian should have this in his office. For the cats to use.",
  "Almost all my family members appreciate various levels of 'heat' in our peppers & sauces. Cookout over Labor Day would make sense.",
  "I could imagine myself using this in a meal that children or other people that don't handle heat well.",
  "Someone who loves to go to food festivals.",
  "Not sure, a special event.",
  "Sometimes it's hard to keep hydrated in the first place, so it sounds like this drink could help. And it's usually better to drink anything but water when you're trying to get hydrated, even though water is one of the best things to get hydrated. So it makes it easier and more motivating in that sense to use save drink packet mixes. Someone who has a difficult time getting vitamins or taking care of themselves, homeless moms maybe, it could help for sure.",
  "You could use it for date night prompts.",
  "I think a couple that has been together a long time... 10 plus years... would get closer together again. We all drift apart with our busy lives and just making an effort to the other can go a long way.",
  "Stay at home moms for sure would relate, and I know because I am one.",
  "Honestly anything. Offering coffee to guests at a party, a quiet meeting with a few friends, or even being with a person who’s going through a hard time and being there for them. It could be something as simple as waking up in the morning with people you love and taking that moment in together, that you’re alive and healthy no matter what the day may bring.",
  "I instantly think of a mother, who wears many hats. The coffee is her little treat that takes her mind somewhere else.",
  "The type of person who would love this product is likely a high-performing, digitally connected individual who pushes their eyes to the limit every day. Such as the Busy Professional, the Gamer or Streamer, the Student or Academic.",
  "Frequent travelers who require portable, dependable glasses.",
  "Any casual teenager. I would suggest this place if me and my buddies were hanging out and had nothing to do.",
  "Someone with strong preferences about what they drink but who isn’t a coffee snob about big brands. Soccer moms, college kids, etc.",
  "Maybe, when you are preparing for a picnic or potluck or something like that.",
  "Any moms or restaurant owners.",
  "It would promoting the weed killer. A gardener would like the product the most.",
  "If you're disabled or don't have much time to plant, that's a new quick way of doing it.",
];

module.exports = { initialReactions, contextPrompts };
