const traits = [
  {
      "_id": "6178f26523c29c21b201d767",
      "gcsFileName": "Foresight.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "title": "Foresight",
      "trait_definition": "Foresight is when someone immediately envisions life situations where this concept will make life better, easier, or more special in some way. The primary indicator of Foresight in one's Initial Reaction is when they don't just tell us their thoughts about the concept or give feedback about it's success potential, but they go on to use their own words to describe who, what, when, how, or why a concept can help them or someone else. The vibe of Foresight should be positive, but does not have to be emotive. In the Initial Reaction, we are not asking participants to tell us \"why\" or \"who\" or \"when\" yet - we've only asked what they think about the idea. Another clear indication of Foresight is when someone says they would or would want to try, buy or use the concept.\n\nThere can also be implied Foresight when there is indication that someone is relating to the concept in a personal way beyond simply giving feedback.The vibe of personal relatability can be subtle, and can be expressed in hindsight or have a futuristic tone. Recollections of previous situations or life moments are often in expressed in hindsight. For example, \"Yes, my dog seems to slow down on long hikes or tire easily\". Foresight can also have a projective rather than personal tone, where they are stating who or when someone else would like, need, use, or benefit from the concept.  \n\nIn summary, for Foresight to be present one of three things should be present - 1) explicit situational who/what/when/where/why context given, and/or 2) expressed interest in or intent to try, use or buy such as \"I would like to try this\", and/or 3) indication of implied relatability beyond someone simply showing that they understand the gist of the concept. \n\nForesight is not present if someone is simply complimenting or restating an explicit element or benefit described in the concept (this would be an \"Intuitive\" vibe only). ",
      "trait_examples": "I think this is a good idea. I like frozen desserts, so this is something I would try. | I love it. One of the biggest things is it prevents eye fatigue which I have a big problem of already so I love that. | It would appeal to my son. | I think it's great it allows me to be my own boss.",
      "traitType": "primary",
      "parentTraits": []
  },
  {
      "_id": "6178f26523c29c21b201d771",
      "gcsFileName": "Positivity.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": true,
      "description": "A positive tone is present",
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "title": "Positivity",
      "traitType": "primary",
      "trait_definition": "The overall vibe is clearly positive or leans positive, or there is a positive tone present in part of the reaction even if something negative is also said. The context could be personal, projective, rational, or emotive, and could range from a simple “yes” or \"good\" to a matter-of-fact compliment or projection of success, to personal emotion being expressed. It's not uncommon for reactions with positivity present to also include some skeptical distraction, or to be polarized where somene is saying something both positive and negative within their whole reaction (e.g. \"I am leery about this because usually I call BS on anything with scent claiming to be all natural, but I really think these scents could work\").",
      "trait_examples": "I would try it. I love Creme Brulee | Sounds good, a little pricey | I think it looks delicious. | Yes, pets and carpet get messy. | I think this is something I would buy! | Yum | It seems very unique and different | It make me want to drink more coffee | Nothing spectacular but straight to the point I liked it",
      "parentTraits": []
  },
  {
      "_id": "6178f26523c29c21b201d769",
      "gcsFileName": "Negativity.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": true,
      "description": "A negative tone is present",
      "hideThemeTag": false,
      "__v": 0,
      "color": "negative",
      "title": "Negativity",
      "trait_definition": "The overall vibe is clearly negative or leans negative, or there is a negative tone present in part of the reaction, regardless of how much is said. The context could be personal, projective, rational, or emotive, and could range from mild criticism or expressed doubtfulness to outright rejection or clear emotive disgust or contempt. The negativity vibe should be directed to the concept itself.  If someone is relating to the problem being solved, that is a positive sign of Problem Relatability, and is not Negativity. High Negativity Vibe signals risk or improvement opportunity, which is why Problem Relatability is not scored as Negativity. Also, mild Distraction can be present without Negativity. For instance, skeptical vibe can be constructive or even hopeful in tone, unclear or fixable vibe also might not feel negative in tone. An example is \"I really like this idea, I hope it's affordable.\" In this instance there is slight skeptical distraction, but no negativity felt toward the concept. Someone might also express a negative tone about people or users, while feeling positive about the concept itself. That said, polarization is common, where someone is expressing both  both Positivity and Negativity in their reaction about the concept (e.g. \"I hate coconut anything, but would try the orange flavor.\")",
      "trait_examples": "Bad idea. | This sounds like what every shampoo brand says, so I think it would fall flat. | I don't do plant based desserts, gross. | This sounds absolutely wonderful! However, sadly, I don't associate employees at McDonalds with barista skills.",
      "traitType": "primary",
      "parentTraits": []
  },
  {
      "_id": "6178f26523c29c21b201d768",
      "gcsFileName": "Intuitive.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "title": "Intuitive",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Intuitive vibe is when there is an indication that this person gets the gist of the concept... Since the Initial Reaction question includes asks \"What do you think of this idea\" and includes prompting in the question: \"For instance, does it appeal to you personally, do you think it could be successful or not?\", even a simple \"yes\" response can be a sign that the participant gets the gist.",
      "trait_examples": "Great idea, so much more sanitary. | Good idea odourless house. | Activia is always successful and they are tasty as well | It's too pricey for me, but the flavors look good | I think it will be successful. Many people need a dairy free option."
  },
  {
      "_id": "627d3a844bcce8cde00dbdb2",
      "gcsFileName": "(INTUITIVE) Good Brand.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d768"
      ],
      "title": "(INTUITIVE) Good Brand",
      "traitType": "secondary",
      "trait_definition": "Intuitive vibe directly associated with positive commentary about the brand shown in the concept.",
      "trait_examples": "So Delicious is a trusted brand with delicious items for sale. | I think it shows Starbucks cares about their customers. | I think this a great brand. I use them all the time and love it!"
  },
  {
      "_id": "6178f26523c29c21b201d75a",
      "gcsFileName": "(INTUITIVE) Ingredient Appeal.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d768"
      ],
      "title": "(INTUITIVE) Ingredient Appeal",
      "traitType": "secondary",
      "trait_definition": "Intuitive vibe directly associated with positive commentary about a specific ingredient used in the product or the ingredients in general.",
      "trait_examples": "I think it would be successful since I also like almond | Natural ingredients with no irritating chemical odors is very appealing | I think it would be successful. Mushrooms are becoming more popular for nutrition and mental health."
  },
  {
      "_id": "6178f26523c29c21b201d751",
      "gcsFileName": "(EMOTIVE DELIGHT) Ingredient Love.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d765"
      ],
      "title": "(EMOTIVE DELIGHT) Ingredient Love",
      "traitType": "secondary",
      "trait_definition": "Emotive Delight directly associated with a specific ingredient used in the product or the ingredients in general.",
      "trait_examples": "It is appealing because it is sweetened with monkfruit! | Love the ingredients that it has | It sounds really good I love natural ingredients | I love macadamia nuts, I think it would be very tasty."
  },
  {
      "_id": "6178f26523c29c21b201d752",
      "gcsFileName": "(FORESIGHT) Expressed Intent.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d767"
      ],
      "title": "(FORESIGHT) Expressed Intent",
      "traitType": "secondary",
      "trait_definition": "Foresight expressed directly as interest or intent to use, try or buy the product or brand described in the concept.",
      "trait_examples": "This product would be very successful and I will buy this product if it becomes available. | I would try it to see if it helped and my cat would use it. | I would buy this dip. | I would give this a try! | I would definitely buy this sandwich for dinner."
  },
  {
      "_id": "627d48e54bcce8cde00dbdc4",
      "gcsFileName": "(FORESIGHT-NICHE) Dietary Issues - Special Diets.h5",
      "contextPromptEnabled": true,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d767",
          "6178f26523c29c21b201d76c",
          "62822026793707eaf32b23fb"
      ],
      "title": "(FORESIGHT-NICHE) Dietary Issues - Special Diets",
      "traitType": "secondary",
      "trait_definition": "Foresight and/or Niche vibe directly associated with the concept perceived to be useful for someone has dietary issues/restrictions or for special diets.",
      "trait_examples": "I like this product since I can't have dairy. | Vegan options are always a good thing and if they taste good, non-vegans will also buy. | I think it would also benefit the hose that consider themselves vegetarian or vegan. | Sounds delicious, I am on KETO diet."
  },
  {
      "_id": "627d474e4bcce8cde00dbdbe",
      "gcsFileName": "(FORESIGHT-NICHE) Gift.h5",
      "contextPromptEnabled": true,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d767",
          "6178f26523c29c21b201d76c",
          "62822026793707eaf32b23fb"
      ],
      "title": "(FORESIGHT-NICHE) Gift",
      "traitType": "secondary",
      "trait_definition": "Foresight and/or Niche vibe directly associated with the concept perceived as a good idea as a gift.",
      "trait_examples": "I think it will sell because it's cute and would make a great gift. | Makes a great gift for a tea lover as well. | I would enjoy trying it and possibly gifting it to a loved one who enjoys coffee."
  },
  {
      "_id": "627d465d4bcce8cde00dbdbc",
      "gcsFileName": "(FORESIGHT-NICHE) Health Conditions.h5",
      "contextPromptEnabled": true,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d767",
          "6178f26523c29c21b201d76c",
          "62822026793707eaf32b23fb"
      ],
      "title": "(FORESIGHT-NICHE) Health Conditions",
      "traitType": "secondary",
      "trait_definition": "Foresight and/or Niche vibe directly associated with the concept perceived as good for someone with any type of health condition or special health needs.",
      "trait_examples": "I think it is a very good idea. I do a lot of cooking for diabetics | I'm interested, it is natural and safe with no chemicals. My cat has skin allergies. | I think it's great - it appeals to me personally, because I love coffee, but was diagnosed with cardiomyopathy."
  },
  {
      "_id": "627d47de4bcce8cde00dbdc0",
      "gcsFileName": "(FORESIGHT-NICHE) Holiday.h5",
      "contextPromptEnabled": true,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d767",
          "6178f26523c29c21b201d76c",
          "62822026793707eaf32b23fb"
      ],
      "title": "(FORESIGHT-NICHE) Holiday",
      "traitType": "secondary",
      "trait_definition": "Foresight and/or Niche vibe directly associated with the concept perceived as good for the holidays, around the holidays, or for holiday-related situations.",
      "trait_examples": "Cinnamon rolls remind me of holidays and family. Good times, warm smells, peace. | Somewhat unique - particularly with Christmas approaching - I would most likely try them | I think it can be successful because pumpkin pie and pepermint bark are popular flavors especially around the holidays and fall."
  },
  {
      "_id": "6178f26523c29c21b201d755",
      "gcsFileName": "(FORESIGHT-NICHE) Kids.h5",
      "contextPromptEnabled": true,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d767",
          "6178f26523c29c21b201d76c",
          "62822026793707eaf32b23fb"
      ],
      "title": "(FORESIGHT-NICHE) Kids",
      "traitType": "secondary",
      "trait_definition": "Foresight and/or Niche vibe directly associated with the concept perceived as good for kids, parents, teens, etc.",
      "trait_examples": "I think I would love for my children to try this product. I believe they would enjoy it. | That sounds like a great idea for big families or people with children. | It would be fun for a family night with kids"
  },
  {
      "_id": "6178f26523c29c21b201d756",
      "gcsFileName": "(FORESIGHT-NICHE) Seasonal.h5",
      "contextPromptEnabled": true,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d767",
          "6178f26523c29c21b201d76c",
          "62822026793707eaf32b23fb"
      ],
      "title": "(FORESIGHT-NICHE) Seasonal",
      "traitType": "secondary",
      "trait_definition": "Foresight and/or Niche vibe directly associated with the concept perceived as good for a specific season.",
      "trait_examples": "I think this product would be successful, especially around the winter time | I would definitely buy it for my dogs, especially in the summer | The idea of seasonal frozen dessert flavors sounds fun and appealing to me, especially the pecan pumpkin pie."
  },
  {
      "_id": "6178f26523c29c21b201d76c",
      "gcsFileName": "Niche.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "fixable",
      "title": "Niche (Initial)",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Niche vibe can be present in Initial Reaction and/or Context Prompt. A comment that expresses or implies that an idea will appeal to an explicit subset of the entire universe of potential consumers.",
      "trait_examples": "Kids would like it as a snack on the way to sporting events or travelling somewhere. | Peppermint is perfect for the holidays and the pecan pumpkin is definitely a fall flavor. | Health conscious, diabetics, or anyone who wants a healthy treat"
  },
  {
      "_id": "627d38414bcce8cde00dbdab",
      "gcsFileName": "(NEUTRALITY-NEGATIVITY) Too Much Work.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "negative",
      "parentTraits": [
          "6178f26523c29c21b201d769"
      ],
      "title": "(NEUTRALITY-NEGATIVITY) Too Much Work",
      "traitType": "secondary",
      "trait_definition": "Negativity or Neutrality vibe directly associated with the belief that this concept might or will be extra work, too much work, too hard, too many steps, or generally just too complicated.",
      "trait_examples": "It doesn't save any time, maybe adds more | I can't imagine doing this all the time"
  },
  {
      "_id": "6179bc0d23c29c21b201d77b",
      "gcsFileName": "(SKEPTICAL) Hopeful Skepticism.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "slightPositive",
      "parentTraits": [
          "6178f26523c29c21b201d772"
      ],
      "title": "(SKEPTICAL) Hopeful Skepticism",
      "traitType": "secondary",
      "trait_definition": "Skeptical vibe that is both positive and emotive, where someone is expressing hopefulness that this concept will truly live up and be as good as it sounds.",
      "trait_examples": "I hope it's as delicious as it looks. | It's a great idea. I hope it works! | Is this for real? Sounds almost too good to be true but if it is, I'm in!"
  },
  {
      "_id": "621d31fdbf20985473169773",
      "gcsFileName": "(SKEPTICAL) Taste Skepticism.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "negative",
      "parentTraits": [
          "6178f26523c29c21b201d772"
      ],
      "title": "(SKEPTICAL) Taste Skepticism",
      "traitType": "secondary",
      "trait_definition": "Skeptical vibe directly associated with perceptions of how they believe or assume the product will or might taste.",
      "trait_examples": "It seems like it would taste bad | I would need to try it to see if it tastes too sweet. | Not not sure about the cinnamon one though."
  },
  {
      "_id": "6178f26523c29c21b201d772",
      "gcsFileName": "Skeptical.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "slightNegative",
      "title": "Skeptical",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Skeptical vibe is characterized by explicit or implied uncertainty about the concept, and can be either rational or emotive in tone.",
      "trait_examples": "Interesting. I'm wondering if using corn is safe. Would the cat try to eat it? How does it absorb more than clay? | I think if it works then that would be awesome."
  },
  {
      "_id": "6178f26523c29c21b201d76f",
      "gcsFileName": "Overpriced.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": true,
      "__v": 0,
      "color": "negative",
      "title": "Overpriced",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Overpriced vibe is an explicit statement indicating they feel the concept is too expensive, overpriced, or not a good enough value for the price shown.",
      "trait_examples": "Way too expensive. | Not worth that high price. | Seems pricey. | The idea is great, but I personally do not like the cost."
  },
  {
      "_id": "6178f26523c29c21b201d773",
      "gcsFileName": "Surprise.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "title": "Surprise",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Surprise is perceived New News expressed with emotion, where someone is conveing a sense of wow, unexpected delight, amazement, or astonishment.",
      "trait_examples": "Wow, so cool, I hope it really works! | This is interesting, I've never seen anything like it! | Are these real?!? They should be!! Oh gosh, what a game changer that would be!!!"
  },
  {
      "_id": "6178f26523c29c21b201d765",
      "gcsFileName": "Emotive Delight.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "title": "Emotive Delight",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Emotive Delight is an explicit or implied presence of positive emotion such as anticipation, joy, happiness, excitement, relief, fondness, gratitude, etc.",
      "trait_examples": "I think this idea is genius! | It sounds good to me! It would solve a big problem! | Looks yummy I love nut butter | Of course it appeals to me. Don't see a downside! | Citrus. Spice. What's not to like!?!? | Yummy! | I think it's a superb idea and I'd love to try them both."
  },
  {
      "_id": "6178f26523c29c21b201d766",
      "gcsFileName": "Fixable.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "fixable",
      "title": "Fixable (Initial)",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Fixable vibe is when somene is suggesting or implying the concept should be changed, improved or fixed in any way, to make it more appealing, more relevant, or to otherwise optimize chances for market success.",
      "trait_examples": "I think you should not mention poop like that so often. Talk about the smell rather than the poop. | I love cold brew & I love green tea; however, I feel like people will not be interested in it. | It's a good idea, but the description is a little wordy. | I like it but I'd add some additional color options."
  },
  {
      "_id": "6178f26523c29c21b201d76a",
      "gcsFileName": "Neutrality.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "neutral",
      "title": "Neutrality",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Neutrality is lack of any positive or negative tone or commentary. The context could range from a simple OK or fine, to expressed or implied ambivalence and indifference to an idea.",
      "trait_examples": ""
  },
  {
      "_id": "6178f26523c29c21b201d76b",
      "gcsFileName": "New News.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "title": "New News",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "New News is an implied or explicit perception that something about this concept feels new, different, novel, distinctive, original, unique, or attention-grabbing in some way.",
      "trait_examples": "Yes, I think it would work, it sounds really innovative. | I love everything about it because it's very eye catching and seems legit. | Something new and different to try. | I think the idea is unique, creative, and innovative. It is the future. I would definitely buy."
  },
  {
      "_id": "6178f26523c29c21b201d76e",
      "gcsFileName": "Not For Me.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": true,
      "__v": 0,
      "color": "negative",
      "title": "Not For Me",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Not For Me is when someone inplies they have prior experience with something about the concept and are generally not into that element.",
      "trait_examples": "This would probably be successful, but I am not into Tequila. | I am not into fast food. | This is a great idea! My sister would eat this stuff up and I think it'd be a hit. But I can't eat dairy, so I would not buy it."
  },
  {
      "_id": "627d33ae4bcce8cde00dbda9",
      "gcsFileName": "(NOT FOR ME) Flavor.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "negative",
      "parentTraits": [
          "6178f26523c29c21b201d76e"
      ],
      "title": "(NOT FOR ME) Flavor",
      "traitType": "secondary",
      "trait_definition": "Not For Me directly associated with a specific flavor or the flavors offered in general.",
      "trait_examples": "Vanilla, chocolate, and coffee are usually too sweet for yogurt for me | I do not like Greek yogurt in any flavor, but especially not coconut"
  },
  {
      "_id": "627d3afb4bcce8cde00dbdb4",
      "gcsFileName": "(FORESIGHT-NICHE) Special Occasion - Event.h5",
      "contextPromptEnabled": true,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d767",
          "6178f26523c29c21b201d76c",
          "62822026793707eaf32b23fb"
      ],
      "title": "(FORESIGHT-NICHE) Special Occasion - Event",
      "traitType": "secondary",
      "trait_definition": "Foresight and/or Niche vibe directly associated with the concept perceived good for for special occasions or events such as birthday parties or weddings.",
      "trait_examples": "I'm sure this would be something people would try for birthday parties, anniversary parties, and special occasions. | It would allow people to make a nice cake for a special occasion at an affordable price | I love how it's mentioned to be used basically as a special occasion item."
  },
  {
      "_id": "627d455a4bcce8cde00dbdb8",
      "gcsFileName": "(FORESIGHT-NICHE) Travel.h5",
      "contextPromptEnabled": true,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d767",
          "6178f26523c29c21b201d76c",
          "62822026793707eaf32b23fb"
      ],
      "title": "(FORESIGHT-NICHE) Travel",
      "traitType": "secondary",
      "trait_definition": "Foresight and/or Niche vibe directly associated with the concept perceived good for for traveling, for travelers, when traveling, etc.",
      "trait_examples": "There is little waste and it would be extremely convenient when traveling | I love to travel so this sounds like a fantastic idea | It is very convient. It would be good for hotels or when you are traveling."
  },
  {
      "_id": "627d45f24bcce8cde00dbdba",
      "gcsFileName": "(FORESIGHT-NICHE) Social Gatherings.h5",
      "contextPromptEnabled": true,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d767",
          "6178f26523c29c21b201d76c",
          "62822026793707eaf32b23fb"
      ],
      "title": "(FORESIGHT-NICHE) Social Gatherings",
      "traitType": "secondary",
      "trait_definition": "Foresight and/or Niche vibe directly associated with the concept perceived good for social gatherings such as family dinners or gatherings with friends, parties, socializing.",
      "trait_examples": "Something I would definitely drink at a bbq with girlfriends! | I believe it would be a good bonding time with family / friends. | I like the ideas of fruits alcoholic beverages they are perfect for the summer and backyard parties."
  },
  {
      "_id": "62822026793707eaf32b23fb",
      "gcsFileName": "Niche (Prompted).h5",
      "contextPromptEnabled": true,
      "initialReactionEnabled": false,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "fixable",
      "title": "Niche (Prompted)",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Can be associated with FORESIGHT or NICHE and therefore could be personal or projective. Explicit mention of the product or concept being beneficial for someone with health conditions",
      "trait_examples": "Examples are the same as Niche Initial."
  },
  {
      "_id": "6178f26523c29c21b201d74c",
      "gcsFileName": "(EMOTIVE DELIGHT) Makes Life Easier!.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d765"
      ],
      "title": "(EMOTIVE DELIGHT) Makes Life Easier!",
      "traitType": "secondary",
      "trait_definition": "Emotive Delight directly associated with the notion of making life easier in some way.",
      "trait_examples": "It would be such an amazing idea and super useful! | As a busy mom, I would love to have my children have the variety of dips for a snack | I think it's an awesome idea and super convenient. | I love it it would help us out so much."
  },
  {
      "_id": "6178f26523c29c21b201d74e",
      "gcsFileName": "(EMOTIVE DELIGHT) Brand Love.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d765"
      ],
      "title": "(EMOTIVE DELIGHT) Brand Love",
      "traitType": "secondary",
      "trait_definition": "Emotive Delight directly associated with fondness for the brand, which can be expressed in hindsight or in a futuristic tone.",
      "trait_examples": "I love World's Best Cat Litter so of course it's a great idea. | I love Starbucks coffee, they always taste wonderful. I would be very eager to try. | Anything McDonald's does is usually yummy! | This is one of my favorite brands, I'd try anything they put out there! | I love this brand."
  },
  {
      "_id": "6178f26523c29c21b201d750",
      "gcsFileName": "(EMOTIVE DELIGHT) Flavor Love.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d765"
      ],
      "title": "(EMOTIVE DELIGHT) Flavor Love",
      "traitType": "secondary",
      "trait_definition": "Emotive Delight directly associated with the flavor or flavors being offered.",
      "trait_examples": "I loooove vanilla! | I especially would be looking forward to the chai flavored one in particular! | The flavors available sound delicious | I love anything flavored with honey. Especially real organic honey unfiltered"
  },
  {
      "_id": "6178f26523c29c21b201d75c",
      "gcsFileName": "(NOT FOR ME) Brand.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "negative",
      "parentTraits": [
          "6178f26523c29c21b201d76e"
      ],
      "title": "(NOT FOR ME) Brand",
      "traitType": "secondary",
      "trait_definition": "Not For Me directly associated with the brand either based on previous experience or general beliefs.",
      "trait_examples": "I've tried this brand before and didn't like it | Activia appeals to older adults with gut health, I personally would not buy Activia products of any kind"
  },
  {
      "_id": "6178f26523c29c21b201d763",
      "gcsFileName": "Blah.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "negative",
      "title": "Blah",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Blah is when someone believes the concept is dull, boring, plain, unexciting, nothing new, lacks distinction and sounds like everyone else, mundane, or generally uncompelling.",
      "trait_examples": "Boring | Sounds like what everyone says | Nothing new here"
  },
  {
      "_id": "6178f26523c29c21b201d774",
      "gcsFileName": "Unclear.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "slightNegative",
      "title": "Unclear",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Unclear vibe is lack of clarity that is either explicit or implied, when someone indicates something about the concept is unclear, does not make sense, or lacks information.",
      "trait_examples": ""
  },
  {
      "_id": "6178f26523c29c21b201d75b",
      "gcsFileName": "(INTUITIVE) Makes Life Easier.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d768"
      ],
      "title": "(INTUITIVE) Makes Life Easier",
      "traitType": "secondary",
      "trait_definition": "Intuitive vibe directly associated with the notion of making life easier in some way - whether it's saving time, money, or anything related to conveinence, etc.",
      "trait_examples": "I want hassle free litter that makes my cat happy as well | I would purchase this. Looks like a much easier way to get probiotics | It would making cooking easier I like it"
  },
  {
      "_id": "6178f26523c29c21b201d75e",
      "gcsFileName": "(NOT FOR ME) Outright Rejection.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "negative",
      "parentTraits": [
          "6178f26523c29c21b201d76e"
      ],
      "title": "(NOT FOR ME) Outright Rejection",
      "traitType": "secondary",
      "trait_definition": "Outright Rejection is a stronger level of Not For Me vibe stated with conviction, when someone is being firm, emotive, or even harsh.",
      "trait_examples": "This is not something I need. | I hate Starbucks, so I'm a no go! | To me litter is litter so as soon as I read premium I was out. | People will probably like it. But I personally think it sounds disgusting!!!!"
  },
  {
      "_id": "6178f26523c29c21b201d764",
      "gcsFileName": "Bust.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "negative",
      "title": "Bust",
      "traitType": "primary",
      "parentTraits": [],
      "trait_definition": "Bust Vibe is an explicit or implied belief that the concept is a bad idea, that the concept will not do well or succeed, or is overwhelmingly unappealing with no viable suggestions for improvement.",
      "trait_examples": ""
  },
  {
      "_id": "627d31924bcce8cde00dbda7",
      "gcsFileName": "(NOT FOR ME) Ingredient.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "negative",
      "parentTraits": [
          "6178f26523c29c21b201d76e"
      ],
      "title": "(NOT FOR ME) Ingredient",
      "traitType": "secondary",
      "trait_definition": "Not For Me directly associated with a specific ingredient or the ingredients in general that are used in the product.",
      "trait_examples": "This has way too much sugar, I would not be interested in buying this product | I doubt my cats would like the lemongrass"
  },
  {
      "_id": "627d39234bcce8cde00dbdad",
      "gcsFileName": "(NEW NEWS) Eye Catching.h5",
      "contextPromptEnabled": false,
      "initialReactionEnabled": true,
      "expandedView": false,
      "hideThemeTag": false,
      "__v": 0,
      "color": "positive",
      "parentTraits": [
          "6178f26523c29c21b201d76b"
      ],
      "title": "(NEW NEWS) Eye Catching",
      "traitType": "secondary",
      "trait_definition": "New News directly associated with the perception that the concept or something about it is attention-grabbing or eye-catching.",
      "trait_examples": "I like the ideas personally. It grabs your attention and informs you | It looks very colorful and fun for my son | I think the packaging is cute which will help it sell in stores"
  }
]

module.exports = { traits };